# Generated by Django 4.2.27 on 2026-06-25 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rgb_car_management.web.managers


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarIssueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("is_other", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name="employee",
            managers=[
                (
                    "objects",
                    rgb_car_management.web.managers.RgbCarManagementUserManager(),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="acceptedcar",
            name="is_ready",
        ),
        migrations.RemoveField(
            model_name="issuedcar",
            name="fixes",
        ),
        migrations.AddField(
            model_name="acceptedcar",
            name="accepting_employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_cars_ae",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuedcar",
            name="mechanic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_cars_m",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="acceptedcar",
            name="issues",
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="CarProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="web.carissuecategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="CarIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "other_issue",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues_category",
                        to="web.carissuecategory",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues_problems",
                        to="web.carproblem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="issuedcar",
            name="repairs",
            field=models.ManyToManyField(related_name="issued_cars", to="web.carissue"),
        ),
        migrations.AddField(
            model_name="acceptedcar",
            name="issues",
            field=models.ManyToManyField(
                related_name="accepted_cars_i", to="web.carissue"
            ),
        ),
    ]
