# Generated by Django 4.2.27 on 2026-06-25 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_carissuecategory_alter_employee_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptedcar",
            name="accepting_employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_cars_ae",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issuedcar",
            name="mechanic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_cars_m",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
