# Generated by Django 4.2.27 on 2026-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_acceptedcar_accepting_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptedcar",
            name="issues",
            field=models.ManyToManyField(
                related_name="accepted_cars", to="web.carissue"
            ),
        ),
    ]
