# Generated by Django 4.2.27 on 2026-06-27 15:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_acceptedcar_issues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptedcar",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_car_car",
                to="web.car",
            ),
        ),
        migrations.AlterField(
            model_name="acceptedcar",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_car_customer",
                to="web.customer",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="registration_number",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(7)],
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="vin_number",
            field=models.CharField(
                max_length=17,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(17)],
            ),
        ),
    ]
